name: Build and Release

on:
  push:
    tags:
      - 'v*' # only trigger on version tags like v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # Add linux-latest if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}